
// IF YOU MAKE ANY MODIFICATIONS TO THE CLASS I STRONGLY RECOMMEND RENAMING IT AS, EVEN IF IN A DIFFERENT BUNDLE, CLASSES OF THE SAME NAME CAN CONFLICT
// TO USE DEFINE A NORMAL PSSLIDERCELL IN YOUR PLIST AND SET CELLCLASS TO BETTERPSSLIDERTABLECELL
// USE OF THIS CODE IN ANY WAY IS PERMITTED, INCLUDING COMMERCIAL USE AND MODIFICATION OF ANY NATURE
// THIS CODE USES ARC - ENABLE BY ADDING ADDITIONAL_CFLAGS = -fobjc-arc TO YOUR MAKEFILE
// CHARLIE HEWITT 2014

@interface BetterPSSliderTableCell : PSSliderTableCell <UIAlertViewDelegate, UITextFieldDelegate> {
  CGFloat minimumValue;
  CGFloat maximumValue;
}
-(void)presentPopup;
@end